# Stoi()

The function stoi converts the sequence of characters in str to a value of type int and returns the value.
For example, when passed a character sequence "10", the value returned by stoi is the integer 10.

Exception Handling in C++
One of the advantages of C++ over C is Exception Handling. Exceptions are run-time anomalies or abnormal conditions that a program 
encounters during its execution. 
There are two types of exceptions: a)Synchronous, b)Asynchronous(Ex:which are beyond the program’s control, Disc failure etc).
C++ provides following specialized keywords for this purpose.
try: represents a block of code that can throw an exception.

catch: represents a block of code that is executed when a particular exception is thrown.
throw: Used to throw an exception. Also used to list the exceptions that a function throws, but doesn’t handle itself.

# Why Exception Handling?

Following are main advantages of exception handling over traditional error handling.

1) Separation of Error Handling code from Normal Code: In traditional error handling codes, 
there are always if else conditions to handle errors. These conditions and the code to handle errors get mixed up with the normal flow. This makes the code less readable and maintainable. With try catch blocks, the code for error handling becomes separate from the normal flow.

2) Functions/Methods can handle any exceptions they choose: A function can throw many exceptions, but may choose to handle some of them. 
The other exceptions which are thrown, but not caught can be handled by caller. If the caller chooses not to catch them, then the exceptions are handled by caller of the caller.
In C++, a function can specify the exceptions that it throws using the throw keyword. 
The caller of this function must handle the exception in some way (either by specifying it again or catching it)

3) Grouping of Error Types: In C++, both basic types and objects can be thrown as exception.
We can create a hierarchy of exception objects, group exceptions in namespaces or classes, categorize them according to types.

# Note
There is a special catch block called ‘catch all’ catch(…) that can be used to catch all types of exceptions. 
For example, in the following program, an int is thrown as an exception, but there is no catch block for int, so catch(…) block will be executed.
